main:
  URI: "ws://127.0.0.1:6700"
  token: "111"
  #机器人掉线自动重连间隔
  auto_reconnect: 60
  #API返回超时时间
  timeout: 30
  #机器人接收websocket信息并行处理最大任务数提醒(用于开发者调试或排除异常)
  #机器人每个事件为单独的线程
  #避免某个插件监听事件处理过于缓慢,影响其他插件监听机器人回复
  #此设置为超过多少接收事件同时处理时在服务器后台输出警告,一般不会超过100
  #看不懂默认即可
  rec_task_tip: 100
  #机器人发送websocket信息同时处理最大数量
  #机器人发送时也会触发事件,发送的信息可被其他插件监听并修改
  #参数设置解释同上
  send_task_tip: 100
#开启后机器人会实时输出websocket通讯
debug: false
#debug消息最大长度
debug_message_max_length: 1000
